### ISSUE TITLE
Add support for Eclipse 2024-03 (4.31.0)

### ISSUE THREAD

**Issue by smitzkus** [gwt-plugins/gwt-eclipse-plugin#483] opened 2024-03-22 16:02 UTC
If you try to install the plugin via the marketplace for eclipse 2024-03 (4.31.0), you get the following error:

`Cannot complete the install because one or more required items could not be found.
  Software being installed: GWT Eclipse Plugin 4.0.0.202302020242 (com.gwtplugins.eclipse.suite.v3.feature.feature.group 4.0.0.202302020242)
  Missing requirement: GWT Eclipse Plugin 4.0.0.202302020242 (com.gwtplugins.gdt.eclipse.suite 4.0.0.202302020242) requires 'osgi.bundle; javax.inject 1.0.0' but it could not be found
  Cannot satisfy dependency:
    From: GWT Eclipse Plugin 4.0.0.202302020242 (com.gwtplugins.eclipse.suite.v3.feature.feature.group 4.0.0.202302020242)
    To: org.eclipse.equinox.p2.iu; com.gwtplugins.gdt.eclipse.suite [4.0.0.202302020242,4.0.0.202302020242]`

**Comment by Edgaras01** [comment] 2024-03-27 09:43
First workaround which I found is to add javax.inject_1.0.0.v20220405-0441.jar (from Eclipse 4.29) to eclipse /plugins/ directory.

**Comment by eliasbalasis** [comment] 2024-03-27 10:10
This is repetition of the following chain:
#482
#481
#480
#474

Adding the missing bundle is one workaround.
The alternative is use of the published repository from the relevant build at https://github.com/gwt-plugins/gwt-eclipse-plugin/actions/runs/7872612432/artifacts/1238411002

**Comment by warwound** [comment] 2024-04-04 14:52
> This is repetition of the following chain: #482 #481 #480 #474
> 
> Adding the missing bundle is one workaround. The alternative is use of the published repository from the relevant build at https://github.com/gwt-plugins/gwt-eclipse-plugin/actions/runs/7872612432/artifacts/1238411002

Hi, your link is now dead.
Can you post a working link for this fix?

**Comment by keinhaar** [comment] 2024-05-17 17:46
I'm logged in, but cannot access the link.

**Comment by eliasbalasis** [comment] 2024-05-19 20:08
![image](https://github.com/gwt-plugins/gwt-eclipse-plugin/assets/1681838/de63fabd-76a6-436c-b97e-acf18184ffea)

I am afraid the build has expired 👎

@protoism 
can you please make another build ? preferably one that does not expire.

**Comment by ssibrahimpur** [comment] 2024-06-18 06:44
Still, the issue exists for the latest version of Eclipse version 2023, 2024

<img width="381" alt="image" src="https://github.com/gwt-plugins/gwt-eclipse-plugin/assets/47515317/7ee09fe2-9d6c-4d47-9fe8-aaef2e5bbceb">


Any plans to fix this?

**Comment by slavap** [comment] 2024-07-23 23:43
Please update this plugin - it is hard to upgrade Eclipse because of it.

**Comment by protoism** [comment] 2024-07-25 09:35
Hi guys,
I'm stuck for lack of approvers.
But it's a matter of days...
This run should be very similar to what I plan to release.

https://github.com/gwt-plugins/gwt-eclipse-plugin/actions/runs/10030276701

The repository is here:

https://github.com/gwt-plugins/gwt-eclipse-plugin/actions/runs/10030276701/artifacts/1723519151

Please consider contributing or at least joining as reviewers.

**Comment by ssibrahimpur** [comment] 2024-07-25 17:04
[like]  Sachin Shivagonda Ibrahimpur reacted to your message:
________________________________

**Comment by ssibrahimpur** [comment] 2024-07-29 07:18
@protoism When do we expect this to be published on Eclipse marketplace?

**Comment by omar-carranza** [comment] 2024-08-01 21:11
Help me please, I have this problem when I install GWT in Eclipse 
![image](https://github.com/user-attachments/assets/b108b19f-3315-4976-b031-7715837e35b8)

**Comment by protoism** [comment] 2024-08-02 08:30
Closing this ticket as the issue is fixed, although not pushed to the marketplace

**Closed** 2024-08-02 08:30 UTC
