### ISSUE TITLE
Eclipse Oxygen.1 Plugin Error due wrong interface

### ISSUE THREAD

**Issue by MCMicS** [gwt-plugins/gwt-eclipse-plugin#365] opened 2017-10-04 19:20 UTC
Eclipse has change an interface.

I have updated from old GWT Plugin to new one but error still occurs

They have added a additional boolean: https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaProject.java

Change comes with: https://github.com/eclipse/eclipse.jdt.core/commit/54049bd43ee6ccfbd3f1b67192d2ed3baee764e3#diff-c1da82ed737689b0aeddf1126c08e061

```com.gwtplugins.gdt.eclipse.core.prefs

java.lang.NoSuchMethodError: org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots([Lorg/eclipse/jdt/core/IClasspathEntry;ZLjava/util/Map;)[Lorg/eclipse/jdt/core/IPackageFragmentRoot;
	at com.google.gdt.eclipse.core.ClasspathUtilities.findRawClasspathEntryFor(ClasspathUtilities.java:163)
	at com.google.gwt.eclipse.core.runtime.GwtSdk$ProjectBoundSdk.findGwtDevClasspathEntry(GwtSdk.java:361)
	at com.google.gwt.eclipse.core.runtime.GwtSdk$ProjectBoundSdk.computeInstallPath(GwtSdk.java:266)
	at com.google.gwt.eclipse.core.runtime.GwtSdk$ProjectBoundSdk.getInstallationPath(GwtSdk.java:189)
	at com.google.gwt.eclipse.core.runtime.GwtSdk.findSdkFor(GwtSdk.java:411)
	at com.google.gwt.eclipse.core.launch.processors.DGwtDevJarArgumentProcessor.maybeGetDevJarPath(DGwtDevJarArgumentProcessor.java:76)
	at com.google.gwt.eclipse.core.launch.processors.DGwtDevJarArgumentProcessor.update(DGwtDevJarArgumentProcessor.java:123)
	at com.google.gdt.eclipse.suite.launch.processors.LaunchConfigurationUpdater.update(LaunchConfigurationUpdater.java:141)
	at com.google.gdt.eclipse.suite.launch.processors.LaunchConfigAffectingChangesListener.syncUpdate(LaunchConfigAffectingChangesListener.java:93)
	at com.google.gdt.eclipse.suite.launch.processors.LaunchConfigAffectingChangesListener.access$2(LaunchConfigAffectingChangesListener.java:89)
	at com.google.gdt.eclipse.suite.launch.processors.LaunchConfigAffectingChangesListener$1.runInWorkspace(LaunchConfigAffectingChangesListener.java:78)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)```

**Comment by branflake2267** [comment] 2017-10-04 19:56
What version of Eclipse are you using?

**Comment by branflake2267** [comment] 2017-10-04 19:57
Thanks for reporting. I haven't noticed this in Oxygen yet. How do you get to this path?

**Comment by MCMicS** [comment] 2017-10-04 20:01
Hi,
I use 4.7.1
I have updated my eclipse and got errors and then try to find the problem. Actually I try to fix it in Branch.

**Comment by branflake2267** [comment] 2017-10-04 20:13
Feel free to provide a patch. I'll take a look either way as I have to go through it and make sure it's compatible across versions before a release. Patches are welcome too. 

Thanks for reporting!

**Comment by MCMicS** [comment] 2017-10-04 20:15
thanks.- I try my best

**Comment by axls** [comment] 2017-10-05 04:29
@MCMicS Maybe you have Groovy Eclipse plugin's snapshot installed (or other plugin that has patched JDT)? I saw the same error with this one. Clean version of Eclipse Oxygene.1 doesn't include JDT version with changes you are mentioned.

**Comment by MCMicS** [comment] 2017-10-05 05:58
Hi axls,
thanks for your clue. But I have no groovy plugin installed. I had made an Update via eclipse instead of clean install. So my JDT Version is different. So this error will occurs with next release Oxygen.1a I think. This is scheduled for end of october.

So this should be fixed before.

Clean install: 
Eclipse Java Development Tools	3.13.1.v20170906-1700

Update:
Eclipse Java Development Tools	3.13.1.v20170928-1310

**Comment by MCMicS** [comment] 2017-10-11 17:53
Question: Why not use `jProject.getAllPackageFragmentRoots();` instead of 

```
IClasspathEntry[] resolvedClasspath = jProject.resolveClasspath(new IClasspathEntry[] {rawClasspathEntry});
IPackageFragmentRoot[] computePackageFragmentRoots = jProject.computePackageFragmentRoots(
            resolvedClasspath, true, null);
```

**Comment by ahs-ckm-server1** [comment] 2017-10-12 11:59
I have just updated to Oxygen.1a because Eclipse suggested to do so and I now have the same problem (no groovy involved). Sounds like a general and important issue without a good workaround that I can see.

**Comment by branflake2267** [comment] 2017-10-12 17:19
Another Oxygen issue, #366

**Comment by branflake2267** [comment] 2017-10-12 17:19
I'm scheduling to work on this tomorrow.

**Comment by stefaneggerstorfer** [comment] 2017-10-12 17:54
Xtext faces the same problem, they fixed this by inlining the old method: https://github.com/eclipse/xtext-eclipse/commit/dcdfcd087ef7efa6b5281d824e9961a47966e322
The old method signature will come back in Oxygen.2 (https://github.com/eclipse/eclipse.jdt.core/commit/93cabc2b1a6103f5b8fc5e200336888a24a95ba5, https://bugs.eclipse.org/bugs/show_bug.cgi?id=525462)

**Comment by MCMicS** [comment] 2017-10-12 18:22
Maybe we need the rollback. I looked on the code yesterday and see no difference in use of `getAllPackageFragmentRoots` method.

But maybe in detail ;)

**Comment by branflake2267** [comment] 2017-10-12 19:25
The issue is fixed and should be in the nightly, anybody try upgrading to the nightly?

**Comment by MCMicS** [comment] 2017-10-13 05:20
not yet testet. will try it on weekend

**Comment by branflake2267** [comment] 2017-10-13 05:42
No worries, I'm going to be aiming to fix this, and figure out the api to use. I'll test both Oxygen and Neon.

**Comment by MCMicS** [comment] 2017-10-13 05:59
ok. I think thts the best way.

**Comment by branflake2267** [comment] 2017-10-13 15:36
So far I've determined the issue is fixed in Eclipse RCP latest Oxygen download. I'm looking at replicating the issue, or figure out that an update fixes it.

**Comment by branflake2267** [comment] 2017-10-13 15:36
Or the oxygen target I'm using it's fixed.

**Comment by branflake2267** [comment] 2017-10-13 15:41
I found the issue on my project now.
![screen shot 2017-10-13 at 8 38 17 am](https://user-images.githubusercontent.com/1326504/31554406-56658344-aff2-11e7-9fe4-dc078a74cd39.png)
![screen shot 2017-10-13 at 8 39 25 am](https://user-images.githubusercontent.com/1326504/31554408-576b7b0e-aff2-11e7-92c4-deee2a7b6210.png)

**Comment by branflake2267** [comment] 2017-10-13 19:19
Fix getting pushed to staging.

**Comment by MCMicS** [comment] 2017-10-13 21:11
*thumpUp*

**Comment by MCMicS** [comment] 2017-10-15 13:26
not see this error anymore with staging version until yet.
seems to fixed

**Comment by branflake2267** [comment] 2017-10-15 15:11
Thanks for getting back. I published it too.

**Comment by izabelrodrigues** [comment] 2017-11-16 19:33
Version: Oxygen.1a Release (4.7.1a)
Build id: 20171005-1200

Today I found this error:
org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots([Lorg/eclipse/jdt/core/IClasspathEntry;ZLjava/util/Map;)[Lorg/eclipse/jdt/core/IPackageFragmentRoot;

is the same error?

My GWT version is 2.5.1

**Comment by branflake2267** [comment] 2017-11-16 23:23
That looks similar. Could you open the error log view and copy the full stack trace and put it here if there is one?

**Comment by Chancafek** [comment] 2017-11-29 13:04
I have the same of @izabelrodrigues with the same Eclipse version - GWT 2.5.1:

Errors running builder 'GWT Project Validator' on project 'Sisa'.
org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots([Lorg/eclipse/jdt/core/IClasspathEntry;ZLjava/util/Map;)[Lorg/eclipse/jdt/core/IPackageFragmentRoot;

`java.lang.NoSuchMethodError: org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots([Lorg/eclipse/jdt/core/IClasspathEntry;ZLjava/util/Map;)[Lorg/eclipse/jdt/core/IPackageFragmentRoot;
	at com.google.gdt.eclipse.core.ClasspathUtilities.findRawClasspathEntryFor(ClasspathUtilities.java:163)
	at com.google.gwt.eclipse.core.runtime.GWTRuntime$ProjectBoundSdk.findGwtDevClasspathEntry(GWTRuntime.java:369)
	at com.google.gwt.eclipse.core.runtime.GWTRuntime$ProjectBoundSdk.computeInstallPath(GWTRuntime.java:269)
	at com.google.gwt.eclipse.core.runtime.GWTRuntime$ProjectBoundSdk.getInstallationPath(GWTRuntime.java:190)
	at com.google.gwt.eclipse.core.runtime.GWTRuntime.findSdkFor(GWTRuntime.java:421)
	at com.google.gwt.eclipse.core.validators.GWTProjectValidator.build(GWTProjectValidator.java:77)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
`

**Comment by branflake2267** [comment] 2017-11-29 14:54
That looks like the same path or issue. My first guess is the plugin is not updated. Do you have the latest update?

**Comment by Chancafek** [comment] 2017-11-29 16:43
Im using GWT 2.5.1 due to compatibily issues in the project. Nevertheless it didnt happen before, I just cant remember what version of Eclipse Oxygen I was using before change the hdd.

**Comment by branflake2267** [comment] 2017-11-30 05:37
Eclipse Oxygen 4.7.1a introduced the issue. The GWT Eclipse plugin was using an internal api, which was faster, but the internal api change broke. I thought I fixed this. I don't think it matters which version of GWT you're using. Worst case, you could use Eclipse mars version to get by. But I suspect if you update Eclipse or reinstall it, it might work.

**Comment by Chancafek** [comment] 2017-12-01 11:48
At the office I work with Eclipse Oxygen 4.7.0 Build: 20170620-1800, tried to use the installer but seems like it does not work anymore due to server's issues (the packages are not longer available). I'll find an offline installer, also Mars version didnt work.

**Comment by branflake2267** [comment] 2017-12-01 16:42
I'll have to look into mars so far I haven't had any other reports yet. I'm going to ramp up and help fix some more bugs, but I think I'm a couple more weeks out still before I can get to this.

**Comment by zecritter** [comment] 2018-02-07 09:10
It seems that error **Errors running builder 'GWT Project Validator'** in Chancafek comment 
https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/365#issuecomment-347854308
is actually in GWT Eclipse Plugin code (**com.google.gwt.eclipse**...). I had this problem too, when installing gwt-eclipse-plugin, it seems GWT Eclipse Plugin is removed from eclipse, but it builders still work in gwt projects...

**Comment by branflake2267** [comment] 2018-02-11 19:37
Could you install and try the Oxygen version? I recommend a stand along independent install for testing with a different workspace so you won't have to upgrade unless you want to. I copy the working directory to test as well.

**Comment by zecritter** [comment] 2018-02-13 11:52
I can confirm, clean Oxygen 4.7.2 with initially empty workspace/configuration + gwt 2.8.2 + stable GWT Eclipse Plugin 3.0.0.201710131939 + imported gwt projects work without problems.

**Closed** 2018-03-21 17:32 UTC
Labels: Fixed - Verify, bug
