### ISSUE TITLE
ClientBundle CssResource - it would be nice to have code navigation to gss file definition.

### ISSUE THREAD

**Issue by slavap** [gwt-plugins/gwt-eclipse-plugin#92] opened 2015-10-03 08:40 UTC
```java
public interface Style extends CssResource {
        String myRule();
}
```
```css
.myRule { ... }
```
When Ctrl Click on myRule() it would be nice to jump into gss file to proper line with definition for it.

**Comment by branflake2267** [comment] 2015-10-31 17:46
This is a duplicate of the .gss editor. Issue 58

**Closed** 2016-08-09 23:40 UTC
Labels: duplicate
