### ISSUE TITLE
Inline GSS editor on UiBinder files doesn't autocomplete CSS3 properties.

### ISSUE THREAD

**Issue by gilberto-torrezan** [gwt-plugins/gwt-eclipse-plugin#79] opened 2015-07-16 19:30 UTC
Related to this question on StackOverflow: http://stackoverflow.com/questions/30823483/how-to-get-autocomplete-of-css3-properties-on-eclipse-inside-the-uistyle-tag

Tested with both the snapshot and the release plugin update sites, on clean Eclipse Luna (4.4.2) installation.

The editor doesn't show auto complete suggestions for CSS3 properties when editing *.ui.xml files (GWT UiBinder). Those suggestions work fine on pure *.gss/*.css files when the CSS profile of the project is set to "CSS3: Cascading Style Sheets, level 3" (under Project > Properties > Web Content Settings > Css profile).

To reproduce the bug:

* Create a GWT project or use an existing one
*  Setup the project to use the CSS3 profile (under Project > Properties > Web Content Settings > Css profile)
* Create a UiBinder file or use an existing one
* Inside the YourFile.ui.xml, create a <ui:style> tag
  * Inside the <ui:style> tag, create a CSS selector, for instance ".myClass"
  * Inside the selector, type, for instance, "border-r" and press ctrl+space for the content assist
  * Only the border-right* properties are shown, not the CSS3 border-radius

```xml
<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">
<ui:UiBinder xmlns:ui="urn:ui:com.google.gwt.uibinder"
xmlns:g="urn:import:com.google.gwt.user.client.ui">

    <ui:style>
        .myClass {
            border-r (ctrl+space... no luck!)
        }
    </ui:style>

</ui:UiBinder>
```
![screenshot from 2015-07-16 16 24 37](https://cloud.githubusercontent.com/assets/7464735/8733005/990c5156-2bd7-11e5-8216-dd63c9c85d8b.png)

When creating the same CSS selector on a *.gss/*.css file, all CSS3 properties are shown without problems.

![screenshot from 2015-07-16 16 26 33](https://cloud.githubusercontent.com/assets/7464735/8733010/a143480c-2bd7-11e5-8de3-b7146df2aa2b.png)

**Comment by branflake2267** [comment] 2015-09-19 22:39
This is on the agenda to enhance. I've got a few bugs I'd like to fix first.

**Comment by branflake2267** [comment] 2015-10-31 17:47
This is a duplicate of https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/58

**Comment by branflake2267** [comment] 2015-12-08 04:33
Closing as this is a duplicate.

**Closed by branflake2267** 2015-12-08 04:33 UTC
Labels: duplicate
