### ISSUE TITLE
Unable to install plugin version 4.0.0 in Eclipse 2023-12 (requires 'osgi.bundle; javax.inject 1.0.0' but it could not be found)

### ISSUE THREAD

**Issue by Explomatic** [gwt-plugins/gwt-eclipse-plugin#474] opened 2023-12-11 19:45 UTC
I recently had to do a fresh install of Eclipse and GWT on my desktop and thus decided to install the newest version of Eclipse, the 2023-12 edition. However, when trying to install the GWT plugin, either directly through the marketplace or through those drag&drop links then I am unable to finish the installation. The error message I get is 

> Missing requirement: GWT Eclipse Plugin 4.0.0.202302020242 (com.gwtplugins.gdt.eclipse.suite 4.0.0.202302020242) requires 'osgi.bundle; javax.inject 1.0.0' but it could not be found

Am I doing something wrong or is there something more to the installation process? I tried looking at the installation process described here and on gwtproject.org, but neither seem to run into this specific issue. I've attached a photo of the full error during the installation process. Note that I am unable to proceed by clicking the Confirm button, simply nothing happens if I try.

![image](https://github.com/gwt-plugins/gwt-eclipse-plugin/assets/14542568/c12565ea-5f9e-4946-a5cb-42ae10035132)

**Comment by keinhaar** [comment] 2023-12-13 23:06
Looks like javax.inject has been dropped and replaced by jakarta.inject in eclipse 2023-12. Please use 2023-09 or 2023-06 until we can fix the issue. Both of them work.

**Comment by eliasbalasis** [comment] 2023-12-19 19:31
I have stumbled upon the same problem.
Unfortunately, 2023-09 is missing some other fixes and may not be suitable for everyone.

I will personally wait for the plugin fix before introducing Eclipse 2023-12 to my teams which are currently stuck at 2021-03 for various reasons.

**Comment by eliasbalasis** [comment] 2023-12-21 09:20
Correction.

I was pleasantly surprised to discover that Eclipse 2023-09 with m2e 2.4.0 seems to be working.

**Comment by jochenw** [comment] 2024-01-04 13:41
The solution, that @keinhaar suggests above seems fairly simple, so I'd expect it to be applicable. Still the problem is present in the nightly build 4.0.1.202305162146. Does this mean, that there hasn't be a nightly build over the last 7 months?

**Comment by JackyDFu** [comment] 2024-01-31 13:27
I can confirm it is possible to install the GWT Eclipse plugin using the commit at the forked repo at https://github.com/keinhaar/gwt-eclipse-plugin/commit/5510a2a195ebd2783884b302fd0534b3cc1ed617.

The following steps are necessary to do so:

1. Clone the repo
2. Execute `mvn verify` with JDK 17
3. Install the plugin in Eclipse using the ZIP-archive "repo/target/targetPlatformRepository/repo-4.0.1-SNAPSHOT.zip"

Note this should be used for test purposes only, as there are possibly further steps necessary.

**Comment by niloc132** [comment] 2024-02-01 15:00
@jochenw the fix that was suggested is still a pending PR, and not having been reviewed/merged, it won't appear in "nightly" builds - which indeed do not run nightly, but on merge to main (and only apply to changes landed on main).

**Comment by keinhaar** [comment] 2024-02-02 07:24
What needs to be done, to get this at least into the nightly?

**Comment by JackyDFu** [comment] 2024-02-02 10:26
So until now I could not see any issues using the suggested fix of @keinhaar. It seems to work as expected.

**Comment by rbernadev** [comment] 2024-02-12 08:26
i have the same problem , is possible to go in night? thanks

**Closed** 2024-02-12 13:39 UTC

**Comment by rbernadev** [comment] 2024-02-12 13:58
excuse me ,  I have always installed the plugins normally, never done as you are saying...
can you explain to me how to do it?

thanks thanks 
(anche io sono italiano)

**Comment by protoism** [comment] 2024-02-12 22:55
Hi @rbernadev, Ciao.

This link has what you're looking for (no need to uncompress!!!!) :

https://stackoverflow.com/questions/5482554/how-to-install-plugin-for-eclipse-from-zip
