### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by sdeanHarris** [gwt-plugins/gwt-eclipse-plugin#397] opened 2020-04-30 16:14 UTC
My stuff was working last week fine and then I rebooted my box and tried to run everything. I am getting the following error and not sure how to debug or even know what is broken. If I build my project from command line and run outside of Eclipse everything is ok. Any ideas or help would be great.

com.google.gwt.thirdparty.guava.common.util.concurrent.UncheckedExecutionException: java.lang.ClassCastException: cannot assign instance of java.lang.Long to field com.google.gwt.dev.jjs.SourceOrigin.fileName of type java.lang.String in instance of com.google.gwt.dev.jjs.SourceOrigin
	at com.google.gwt.thirdparty.guava.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:2060)
	at com.google.gwt.thirdparty.guava.common.util.concurrent.Futures.getUnchecked(Futures.java:2045)
	at com.google.gwt.dev.MinimalRebuildCacheManager.syncReadDiskCache(MinimalRebuildCacheManager.java:264)
	at com.google.gwt.dev.MinimalRebuildCacheManager.getCache(MinimalRebuildCacheManager.java:104)
	at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:357)
	at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:175)
	at com.google.gwt.dev.codeserver.Recompiler.recompile(Recompiler.java:134)
	at com.google.gwt.dev.codeserver.Outbox.recompile(Outbox.java:135)
	at com.google.gwt.dev.codeserver.JobRunner.recompile(JobRunner.java:113)
	at com.google.gwt.dev.codeserver.JobRunner.access$000(JobRunner.java:37)
	at com.google.gwt.dev.codeserver.JobRunner$2.run(JobRunner.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: cannot assign instance of java.lang.Long to field com.google.gwt.dev.jjs.SourceOrigin.fileName of type java.lang.String in instance of com.google.gwt.dev.jjs.SourceOrigin
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2233)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1405)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2284)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2202)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at com.google.gwt.dev.jjs.JsSourceMap.readObject(JsSourceMap.java:77)
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at java.util.HashMap.readObject(HashMap.java:1409)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2278)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2202)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at com.google.gwt.dev.MinimalRebuildCacheManager$2.call(MinimalRebuildCacheManager.java:176)
	at com.google.gwt.dev.MinimalRebuildCacheManager$2.call(MinimalRebuildCacheManager.java:162)
	... 4 more

**Comment by protoism** [comment] 2023-01-31 16:40
I think that this issue has nothing to do with the plugin.
Maybe more related to GWT.
@niloc132 am I right?

**Comment by niloc132** [comment] 2023-01-31 23:28
Yes, this is likely caused by either mixing classpath with old and new GWT, or more likely updating the GWT version but keeping the gwt-unitCache around.

Given the age of the issue and no one else reporting this, I'll close this for now, but please reopen if you see it again.

**Closed by niloc132** 2023-01-31 23:28 UTC
