### ISSUE TITLE
Error installing from market place because of javax.inject which was moves to jakarta.inject

### ISSUE THREAD

**Issue by gtabakman** [gwt-plugins/gwt-eclipse-plugin#481] opened 2024-03-17 11:22 UTC
![inject](https://github.com/gwt-plugins/gwt-eclipse-plugin/assets/986930/de1eead3-4526-47dc-9c82-7ac58cb24fd8)

**Comment by eliasbalasis** [comment] 2024-03-17 18:04
This looks like a duplicate of #474 and #480

I have used the direct link to the downloadable repository
at https://github.com/gwt-plugins/gwt-eclipse-plugin/actions/runs/7307950625/artifacts/1132518816
but https://github.com/gwt-plugins/gwt-eclipse-plugin/actions/runs/7872612432/artifacts/1238411002 should work the same

**Closed** 2024-03-17 21:05 UTC

**Comment by gtabakman** [comment] 2024-03-18 17:24
I don't understand why it is closed as completed.
I just tried it again and I get the same Error

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by niloc132** [comment] 2024-03-18 18:30
The ticket is closed because the work is completed, but a release still needs to be made. The changes are in main, and since they've merged, the ticket is marked fixed - we don't hold all tickets open until the release is cut.

Did you try the links above to get a build from CI?

**Comment by gtabakman** [comment] 2024-03-19 05:52
Thanks for the explanation,
I will try the links but I think that I will wait for a release.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
